FROM ubuntu:latest

RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && \
    chmod +x cloudflared-linux-amd64 && \
    mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

ENTRYPOINT ["cloudflared", "tunnel", "--url", "http://localhost:8080"]
CMD []
EXPOSE 8080