---
apiVersion: v1
kind: Service
metadata:
  name: websocket-exfil-uploader-service
  labels:
    app: websocket-exfil
spec:
  type: NodePort
  selector:
    app: websocket-exfil # This matches the 'app' label in your Deployment's Pod template
  ports:
    - protocol: TCP
      port: 8080       # The port the service exposes
      targetPort: 8080 # The port your 'uploader' container listens on
      nodePort: 30080  # Optional: You can specify a NodePort (must be in the 30000-32767 range)
                       # If omitted, Kubernetes will assign one automatically
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-exfil-downloader-service
  labels:
    app: websocket-exfil
spec:
  type: NodePort
  selector:
    app: websocket-exfil # This matches the 'app' label in your Deployment's Pod template
  ports:
    - protocol: TCP
      port: 8081       # The port the service exposes
      targetPort: 8081 # The port your 'downloader' container listens on
      nodePort: 30081  # Optional: You can specify a NodePort (must be in the 30000-32767 range)
                       # If omitted, Kubernetes will assign one automatically